# Mostly copied from https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant
# zlatinb

name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: GetText
        run: sudo apt install gettext
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name : Generate override.properties
        run: |
          rm -f override.properties
          echo "build.built-by=GitHub Actions" >> override.properties
          echo "noExe=true" >> override.properties
      - name: build with Ant
        run: ant distclean pkg
      - name: Upload installer.jar
        uses: actions/upload-artifact@v4
        with:
          name: I2P-install.jar-${{ github.sha }}
          path: install.jar
  
  javadoc-latest:
    runs-on: ubuntu-latest

    steps:
      - name: GetText
        run: sudo apt install gettext
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name : Generate override.properties
        run: |
          rm -f override.properties
          echo "build.built-by=GitHub Actions" >> override.properties
          echo "noExe=true" >> override.properties
      - name: build with Ant
        run: ant distclean javadoc
      - name: zip javadoc
        run: zip -r javadoc.zip build/javadoc
      - name: Upload javadoc.zip
        uses: actions/upload-artifact@v4
        with:
          name: I2P-javadoc-${{ github.sha }}.zip
          path: javadoc.zip

